baseURL = 'https://pratikstemkar.github.io/'
languageCode = 'en-us'
title = 'Pratik Temkar'
theme="cactus"

[params]
  colortheme = "classic" # dark, light, white, or classic
  description = "Hi, I am Pratik. I am a Software Engineer interested in designing complex systems and scaling them. I have a good grasp on Data Structures & Algorithms with System Design. I'm language agnostic and am always ready to pick up a new technology. I am passionate about sharing everything I learn through my blogs and videos."
  mainSection = "posts"
  mainSectionTitle = "Blogs"
  showAllPostsOnHomePage = false
  postsOnHomePage = 5
  tagsOverview = false
  tocInline = true
  showProjectsList = true
  projectsUrl = "https://github.com/pratikstemkar"
  googleAnalyticsAsync = true
  rss = true
  mathjax = true

[[params.social]]
  name = "twitter"
  link = "https://www.x.com/pratikstemkar/"

[[params.social]]
  name = "github"
  link = "https://github.com/pratikstemkar"

[[params.social]]
  name = "email"
  link = "pratikstemkar@gmail.com" # no need for "mailto:" at the start

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/pratikstemkar/"

[[params.social]]
  name = "youtube"
  link = "https://www.youtube.com/@pratikstemkar/"

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Blogs"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

googleAnalytics = "G-QF832JE57H"